notifications:
  email:
    - laszewski@gmail.com
    - shenoy.200@gmail.com
    - vaglomangirish@gmail.com
    - kevinwangfg@gmail.com
    
git:
  submodules: false

virtualenv:
  system_site_packages: true

#os:
#  - linux
#  - osx

language: python

python:
  - "2.7"

# libraries:
# - name: pycrypto
#   version: "2.7.11"
  
install:
  - sudo apt-get update
  - sudo apt-get install build-essential checkinstall
  - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev
  - sudo apt-get libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
  - wget https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
  - tar xzf Python-2.7.10.tgz
  - cd Python-2.7.10
  - sudo ./configure
  - sudo make altinstall
  - python --version
  - cd ..
  - mkdir ~/.cloudmesh
  - pip install --upgrade pip
  - pip --version
  - pip install pyyaml --upgrade --force
  - pip install lockfile
  - curl -L http://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz | tar xz
  - cd pycrypto-2.6.1
  - python setup.py install
  - cd ..
  - git clone https://github.com/cloudmesh/client.git
  - cd client
  - pip install -r requirements.txt
  - pip install -r requirements-doc.txt
  - pip install -r requirements-test.txt
  - python setup.py install --verbose
  - ln -s `pwd` $(dirname `which python`)/../lib/python2.7/site-packages/cloudmesh_client

script:
  - cd ~
  - pwd
  - ls
  - ls bin
  - cm version
  - nosetests -v --nocapture tests/cm_basic
#  -  py.test tests/cm_basic
#  - make doc
#  - cm help
