notifications:
  email:
    - laszewski@gmail.com
    - shenoy.200@gmail.com
    - vaglomangirish@gmail.com
    - kevinwangfg@gmail.com
    
git:
  submodules: false

virtualenv:
  system_site_packages: true

#os:
#  - linux
#  - osx

language: python

python:
  - "2.7"

# libraries:
# - name: pycrypto
#   version: "2.7.11"
  
install:
  - pip install --upgrade pip
  - pip --version
  - pip install pyyaml --upgrade --force
  - pip install lockfile
  - curl -L http://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz | tar xz
  - cd pycrypto-2.6.1
  - python setup.py install
  - cd ~
  - mkdir ~/.cloudmesh
  - mkdir -p ~/github/cloudmesh
  - cd ~/github/cloudmesh
  - git clone https://github.com/cloudmesh/client.git
  - cd client
  - pip install -r requirements.txt
  - pip install -r requirements-doc.txt
  - pip install -r requirements-test.txt
  - python setup.py install
  - ln -s `pwd` $(dirname `which python`)/../lib/python2.7/site-packages/cloudmesh_client

script:
  - cm help
  - py.test tests/cm_basic
#  - nosetests -v --nocapture tests/cm_basic
#  - make doc
#  - cm help
